spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/hwtracker-verify-tasks
  application:
    name: hwtracker-scanner
server:
  port: 8120

springfox:
  documentation:
    openApi:
      v3:
        path: /hwtracker/documentation/v3/api-docs
    swagger:
      v2:
        path: /hwtracker/documentation/v2/api-docs

com:
  hwtracker:
    githubscanner:
      schedule:
        cronrate: "0 0 0/1 1/1 * ?"