spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/hwtracker-homework
  application:
    name: hwtracker-data-core
server:
  port: 8130

springfox:
  documentation:
    openApi:
      v3:
        path: /hwtracker/documentation/v3/api-docs
    swagger:
      v2:
        path: /hwtracker/documentation/v2/api-docs
