spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/hwtracker
  application:
    name: hwtracker-data-core
server:
  port: 8110

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,logfile,metrics,info

springfox:
  documentation:
    openApi:
      v3:
        path: /hwtracker/documentation/v3/api-docs
    swagger:
      v2:
        path: /hwtracker/documentation/v2/api-docs
